### ISSUE TITLE
Button action

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#16]
Hi, how can I activate a command without clicking on a button, but for example a table cell, since there is a video and I want to stop the player?
![image](https://user-images.githubusercontent.com/15727518/91323272-5f356900-e7c9-11ea-8e00-fede46dd40c7.png)

**Comment by yoheimuta** [comment]
dup: https://github.com/yoheimuta/RxMusicPlayer/issues/17
