### ISSUE TITLE
Button action tap

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#17]
Hi, how can I activate a command without clicking on a button, but for example a table cell, since there is a video and I want to stop the player?
![image](https://user-images.githubusercontent.com/15727518/91552481-907e7800-e934-11ea-9f41-936ce49c7d53.png)

**Comment by yoheimuta** [comment]
@rastaman111 You can send a command using a variety of RxSwift components in addition to the button event.
For example, PublishRelay is useful to activate the player freely like below. It mainly has one method "accept."

```diff
diff --git a/Example/TableViewController.swift b/Example/TableViewController.swift
index 515c802..7b86ffa 100644
--- a/Example/TableViewController.swift
+++ b/Example/TableViewController.swift
@@ -152,8 +157,14 @@ class TableViewController: UITableViewController {
             .drive()
             .disposed(by: disposeBag)
 
+        let relay = PublishRelay<RxMusicPlayer.Command>()
+        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
+            relay.accept(.play)
+        }
+
         // 3) Process the user's input
         let cmd = Driver.merge(
+            relay.asDriver { _ in .empty() },
             playButton.rx.tap.asDriver().map { [weak self] in
                 if self?.playButton.currentTitle == "Play" {
                     return RxMusicPlayer.Command.play
```

**Comment by rastaman111** [comment]
@yoheimuta thank you, it works

**Comment by rastaman111** [comment]
Hi @yoheimuta  
I have this function, I send commands to the player through it, but when I send commands, a bug occurs on the lock screen, you press pause and play again, then the track starts playing from the beginning

self.relayCommandPlayer(.seek(seconds: Int(second), shouldPlay: true))

<img width="546" alt="Image" src="https://github.com/user-attachments/assets/70ab9141-9fc4-456a-8b7c-0390c4ad8517" />

**Comment by rastaman111** [comment]
How do I send a rewind command from anywhere in the app?
