### ISSUE TITLE
No such module 'RxCocoa'

### ISSUE THREAD

**Issue by DyoungYu** [yoheimuta/RxMusicPlayer#18]
I can't run successfully because xcode reports an error “No such module 'RxCocoa”,  Excuse me, what should I do？

**Comment by yoheimuta** [comment]
@DyoungYu RxMusicPlayer depends on RxCocoa which is a part of the RxSwift family.
Let me know how you installed RxMusicPlayer into your project.

I think it should set up dependencies correctly if you install it via Carthage or CocoaPods by following [the README](https://github.com/yoheimuta/RxMusicPlayer#installation).
