### ISSUE TITLE
An AVPlayerItem cannot be associated with more than one instance of AVPlayer

### ISSUE THREAD

**Issue by Shishani58** [yoheimuta/RxMusicPlayer#21]
The error occurs with long tracks (30-50 mins) if you switch tracks quickly. You can reproduce this bug by changing the urls to other ones, with a long duration (in example app).

**Comment by rastaman111** [comment]
I also have this, but not always

**Comment by Shishani58** [comment]
I think it is related to audio streaming or downloading. After downloading a track, this problem disappears

**Comment by yoheimuta** [comment]
@Shishani58 Sorry for the late reply. 
Thank you for reaching out!
I'm looking into it.

**Comment by Shishani58** [comment]
@yoheimuta 
I found out that this bug is related to metadata. If you set the metadata manually, the problem does not occur

**Comment by yoheimuta** [comment]
@Shishani58 I haven't reproduced it as maybe I found only 6 ~ 8-min long tracks(royalty-free) from https://www.bensound.com/royalty-free-music?sort=p.sku&order=DESC.

Can you share those long tracks with me? In particular, the ones with a relaxing license are better.

**Comment by dinhthiet2702** [comment]
i get the same error if user press next too fast and many times, then they press play and keep doing the same until crash, how to fix that please help me!

**Comment by yoheimuta** [comment]
https://github.com/yoheimuta/RxMusicPlayer/issues/53 might be related.

**Comment by yoheimuta** [comment]
@dinhthiet2702 Thank you for telling me.
I fixed the issue at [v2.3.3](https://github.com/yoheimuta/RxMusicPlayer/releases/tag/2.3.3).
