### ISSUE TITLE
Put all the songs in UITableView 

### ISSUE THREAD

**Issue by niraj547** [yoheimuta/RxMusicPlayer#22]
Hi
I have a question, hope you can help, I wanted to put all songs in UITable view and play only if the cell is tapped or the button inside the cell is tapped. Is that possible RxMusicPlayer??

Thanks

**Comment by rastaman111** [comment]
hi yes i did the same

**Comment by niraj547** [comment]
Can u give me some examples because I tried and the same song is repeated in each row. That would be great help

Thanks

**Comment by rastaman111** [comment]
I threw an array of links into a table and when I clicked on a cell, I took a certain link and sent it to the player
