### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#24]
Hey! When installing Pod issues an error when compiling the project
<img width="665" alt="Снимок экрана 2021-03-31 в 13 06 57" src="https://user-images.githubusercontent.com/15727518/113128229-43dc8180-9222-11eb-8d5d-c99d33e3b121.png">
<img width="707" alt="Снимок экрана 2021-03-31 в 13 08 21" src="https://user-images.githubusercontent.com/15727518/113128236-450dae80-9222-11eb-9d30-d3daef60fdaf.png">
<img width="708" alt="Снимок экрана 2021-03-31 в 13 08 32" src="https://user-images.githubusercontent.com/15727518/113128243-463edb80-9222-11eb-9b92-f5d1dd557bfc.png">

**Comment by StefaniOSApps** [comment]
@rastaman111 
fork this repo and replace this with
`observer(.failure(error ?? NSError()))`

**Comment by yoheimuta** [comment]
@rastaman111 Thank you for reaching out!
I'm getting to this fix this weekend.

**Comment by yoheimuta** [comment]
@rastaman111 I fixed it by 2.0.0.
Can you confirm it works?

- ref. https://github.com/yoheimuta/RxMusicPlayer/releases/tag/2.0.0

**Comment by rastaman111** [comment]
checked, everything works
