### ISSUE TITLE
Dear author,

### ISSUE THREAD

**Issue by brandy2015** [yoheimuta/RxMusicPlayer#3]
This is a really great RxPlayer. But how can I play the music when the first time I come in this player ViewController, Or control the player in other View?

**Comment by yoheimuta** [comment]
@brandy2015 Thank you for reaching out!

While I might not understand your point correctly, I will explain how to play music when the hosting ViewController appears.

Here is the diff in the project demo code, which you can apply to achieve it.

```diff
        // 3) Process the user's input
        let cmd = Driver.merge(
            playButton.rx.tap.asDriver().map { [weak self] in
                if self?.playButton.currentTitle == "Play" {
                    return RxMusicPlayer.Command.play
                }
                return RxMusicPlayer.Command.pause
            },
            nextButton.rx.tap.asDriver().map { RxMusicPlayer.Command.next },
            prevButton.rx.tap.asDriver().map { RxMusicPlayer.Command.previous },
            seekBar.rx.controlEvent(.valueChanged).asDriver()
                .map { [weak self] _ in
                    RxMusicPlayer.Command.seek(seconds: Int(self?.seekBar.value ?? 0),
                                               shouldPlay: false)
                }
                .distinctUntilChanged()
        )
+       .startWith(.play)
        .debug()
```

- ref. https://github.com/yoheimuta/RxMusicPlayer#example

Let me know when you still have a problem.

**Comment by brandy2015** [comment]
Thank you very much. I will try that out.

**Comment by yoheimuta** [comment]
@brandy2015 I'm closing this issue because time has already passed.
