### ISSUE TITLE
example with SwiftUI

### ISSUE THREAD

**Issue by stfenjobs** [yoheimuta/RxMusicPlayer#30]
hi 
can you add an example use SwiftUI ?

thank you very much

**Comment by yoheimuta** [comment]
@stfenjobs Thank you for reaching out.
I added an example built on SwiftUI at https://github.com/yoheimuta/RxMusicPlayer/tree/master/ExampleSwiftUI.

Can you confirm it?

**Comment by stfenjobs** [comment]
@yoheimuta 

thank you very much
