### ISSUE TITLE
how to play local file ?

### ISSUE THREAD

**Issue by stfenjobs** [yoheimuta/RxMusicPlayer#34]
my code based on `https://github.com/yoheimuta/RxMusicPlayer/tree/master/ExampleSwiftUI`

i add 3 mp3 files to my project

then  i change  the `items` 
 in  here`https://github.com/yoheimuta/RxMusicPlayer/blob/master/ExampleSwiftUI/PlayerView.swift#L41`

here's my code:

![image](https://user-images.githubusercontent.com/6580897/122667167-07e30800-d1e4-11eb-8b02-6e763804c0b6.png)

but, it can't play mp3 file

can you help me?

thank you very much

**Comment by yoheimuta** [comment]
@stfenjobs How about this update?

- ref. https://github.com/yoheimuta/RxMusicPlayer/pull/35/files

**Comment by stfenjobs** [comment]
@yoheimuta 
thank you very much
