### ISSUE TITLE
Loading state although the player is playing

### ISSUE THREAD

**Issue by StefaniOSApps** [yoheimuta/RxMusicPlayer#36]
I have the problem that the following `RxMusicPlayer.Status` are deliver for remote audio url after play tap:

- loading
- loading
- playing
- loading

However, the player is playing and is not in the prefetching state (see last state). Why is this happening?

**Comment by yoheimuta** [comment]
@StefaniOSApps Sorry for this late reply.
I couldn't reproduce your problem locally while just running [the example project](https://github.com/yoheimuta/RxMusicPlayer/tree/master/ExampleSwiftUI).

I looked at the status change in the console output [here](https://github.com/yoheimuta/RxMusicPlayer/blob/master/ExampleSwiftUI/PlayerView.swift#L155).

How should I set it up to confirm your problem?
Can you give me something useful to reproduce it like the small reproducible project or the video capture on the simulator?
