### ISSUE TITLE
Add more functionality to rewind audio (15, 30) seconds

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#40]
Add more functionality to rewind audio (15, 30) seconds, so that the user can assign it himself how much it would be convenient for him

MPRemoteCommandCenter.shared().skipForwardCommand and
MPRemoteCommandCenter.shared().skipBackwardCommand

**Comment by rastaman111** [comment]
@yoheimuta Help

**Comment by yoheimuta** [comment]
It seems like there's no way to display all the features at once.
I plan to add a new parameter with which developers can turn on one of two features: moving track (current) or rewinding (new).

- [memo] Registering duplicate MPRemoteCommandCenter.shared().skipForwardCommand enables either one. Therefore, it's reasonable to accept a value of the second to skip to a specified position like 15 or 30.

| Current                                                                                                                                                                                                                       | New addition                                                                                                                                                                                                                  |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/1223268/145736147-2a3fc4b9-18e4-4f33-9126-55abc52f9317.png) ![image](https://user-images.githubusercontent.com/1223268/145736145-51704494-0e4b-49b9-9074-a3c657ed1572.png) |  ![image](https://user-images.githubusercontent.com/1223268/145736143-bde53527-20ac-4aa4-b826-ba6494ed8f3b.png) ![image](https://user-images.githubusercontent.com/1223268/145736148-fcf6edf0-0733-4238-81c5-1aa202de69b5.png) |

**Comment by rastaman111** [comment]
Hello.  Yes, you can only show one thing.  as an option, the user can save in UserDefaults what he needs and also save what interval to rewind.  something should be of this type: a variable that determines what to show and two variables responsible for fast forward and rewind

**Comment by rastaman111** [comment]
[44](https://github.com/yoheimuta/RxMusicPlayer/issues/44)

and also in the player itself, you need to add 2 functions so that the user can add rewind both before and back
