### ISSUE TITLE
how can I update all URLs in the player?

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#41]
I can edit the audio metadata in my application, how can I update all URLs in the player?

Most likely, new functionality is needed, since after editing I delete the original url and add a new url

**Comment by yoheimuta** [comment]
@rastaman111 Can you elaborate?

There are APIs to append, insert, and remove an item.

- ref. https://github.com/yoheimuta/RxMusicPlayer/issues/28#issuecomment-842742832

**Comment by rastaman111** [comment]
> Can you elaborate?
> 
> There are APIs to append, insert, and remove an item.
> 
> ref. Add MP3 Urls by Button while playing #28 (comment)

adding and removing elements I know what exists, but it would be possible to implement this: I have an array of 3 elements, I edited 1 element and after editing the system itself deletes the old url and creates a new one, as a result, I get the same 3 elements in the array at the output

**Comment by yoheimuta** [comment]
A new pull request is welcome.
I'm not sure it's a priority feature I haste to implement it.
