### ISSUE TITLE
Time format considering the hour notation like "%H:%M:%S" instead of "%M:%S"

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#45]
@yoheimuta I noticed a hundred if the length is more than one hour, then the time is displayed incorrectly

![image](https://user-images.githubusercontent.com/15727518/140618411-6dc7be59-3395-4316-aa11-509e57b69d85.jpeg)

**Comment by rastaman111** [comment]
![image](https://user-images.githubusercontent.com/15727518/140621044-3621fb07-515f-4b17-9513-ef30feed3b07.jpeg)

**Comment by rastaman111** [comment]
Hi @yoheimuta. When can you update this issue and #43

**Comment by rastaman111** [comment]
Hey @yoheimuta!  How soon will you make this change?

**Comment by rastaman111** [comment]
public var displayTime: String? {
        guard let sec = seconds?.rounded().toInt() else { return nil }
        return String(format: "%d:%02d", sec / 60, sec % 60)
    }

convert:

extension Double {
    func formatTime(style: DateComponentsFormatter.UnitsStyle) -> String {
        let durationFormatter = DateComponentsFormatter()
        
        durationFormatter.unitsStyle = style
        durationFormatter.allowedUnits = [.minute, .second]
        durationFormatter.zeroFormattingBehavior = .pad
        durationFormatter.collapsesLargestUnit = false
        
        if abs(self) > 3599.0 {
            durationFormatter.allowedUnits = [.hour, .minute, .second]
        }
        
        return durationFormatter.string(from: self)!
    }
}

**Comment by yoheimuta** [comment]
@rastaman111 I changed the title. Is it more correct?
Title accuracy influences my attention.

I'm willing to support this use case. 
Before the support, you have a workaround to edit "displayTime" yourself.

**Comment by rastaman111** [comment]
I implemented this solution as in the screenshot, since it works correctly, it shows the Clock index when needed

**Comment by yoheimuta** [comment]
@rastaman111 The screenshot doesn't tell me the desired result. It's a source code.

Can you fill in words below?

- When I pass __ as input, I want to get __ as output, but I got __.

**Comment by rastaman111** [comment]
I installed the player via Pod and changed your function to the one on the screen and it works as it should

![image](https://user-images.githubusercontent.com/15727518/145702124-36af4f65-160a-4f5b-9437-6862e1762aac.png)
![image](https://user-images.githubusercontent.com/15727518/145702153-7bb14db7-5a15-451f-a3c4-41c62db118c1.png)
![image](https://user-images.githubusercontent.com/15727518/145702156-ba3085fb-5404-4fdb-b667-734cbe085a87.png)
