### ISSUE TITLE
Error skip

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#49]
Hey!  I want to rewind the player 15 seconds forward and backward on the player screen, how can I do this?  when I take real seconds + 15 and do seek it works, but when the audio ends and should switch to the next track it gives an error

**Comment by yoheimuta** [comment]
@rastaman111 You can use a skip command. `.skip(seconds: 15)` and `.skip(seconds: -15)`

- ref. https://github.com/yoheimuta/RxMusicPlayer/blob/9f6848c8bad5fde6475f3d3f2e9d44056612d4a0/ExampleSwiftUI/PlayerView.swift#L201

**Comment by rastaman111** [comment]
![image](https://user-images.githubusercontent.com/15727518/147381790-14bd6abc-db23-4483-a69b-2812505f0c93.jpeg)

I have such a function, and in the input data I enter .skip (15), and when switching to a new track, the application crashes

**Comment by rastaman111** [comment]
<img width="504" alt="Снимок экрана 2021-12-25 в 17 44 17" src="https://user-images.githubusercontent.com/15727518/147387504-cc8568ec-4c68-449a-a100-ee1247e59b31.png">
