### ISSUE TITLE
"Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler" error when building Example

### ISSUE THREAD

**Issue by KylChiang** [yoheimuta/RxMusicPlayer#5]
I got an error: /Users/Me/Documents/gist/RxMusicPlayer/RxMusicPlayer/RxMusicPlayer+Rx.swift:10:8: Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /Users/Me/Documents/gist/RxMusicPlayer/Carthage/Build/iOS/RxCocoa.framework/Modules/RxCocoa.swiftmodule/arm64.swiftmodule

And after I update carthage file with RxSwift version 5.0.0, still the same.
I have been searched some solutions but not clear for me 😭 
Is this problem means the RxSwift framework is using Swift 5.1.2, so I have to upgrade my Swift version from 5.0.0?

**Comment by yoheimuta** [comment]
@KylChiang Thank you for your report.

I guess you have to rebuild the library manually.
Could you give it a try to run the command below?

```bash
carthage update --no-use-binaries --platform iOS R.swift.Library
```

**Comment by KylChiang** [comment]
Hi Yoheimuta,

Yes, it's fixed and works charming.
Thanks a lot!
