### ISSUE TITLE
Fatal Error in Firebase Crashlytics

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#53]
<img width="751" alt="Снимок экрана 2022-01-15 в 13 15 31" src="https://user-images.githubusercontent.com/15727518/149618256-380f0a88-6274-41ab-b6d6-74761927bcb2.png">
<img width="607" alt="Снимок экрана 2022-01-15 в 13 15 46" src="https://user-images.githubusercontent.com/15727518/149618258-b7f53897-e9e1-40e4-aec3-b5e8066a62c0.png">
<img width="592" alt="Снимок экрана 2022-01-15 в 13 16 03" src="https://user-images.githubusercontent.com/15727518/149618259-483e328c-4ca3-4207-97eb-d8a155813f9a.png">
<img width="1206" alt="Снимок экрана 2022-01-15 в 13 16 48" src="https://user-images.githubusercontent.com/15727518/149618260-a1b3771d-1076-44b2-be19-abd74c6c8bcc.png">
<img width="1213" alt="Снимок экрана 2022-01-15 в 13 17 20" src="https://user-images.githubusercontent.com/15727518/149618261-d861b574-b308-4aed-96c6-b236cf3e6965.png">

**Comment by rastaman111** [comment]
I once caught this bug, my actions: I have a table with local files and clicked on one of them and a bug occurred

**Comment by yoheimuta** [comment]
@rastaman111 Thank you for reporting the crash.
However, I think this information only is insufficient to look into the cause because the source code location at RxMusicPlayer got lost. I don't have the faintest idea at the moment.

**Comment by yoheimuta** [comment]
@rastaman111 I fixed an obvious race condition issue at [v2.3.3](https://github.com/yoheimuta/RxMusicPlayer/releases/tag/2.3.3).
Can you use this version or later?

**Comment by yoheimuta** [comment]
When you observe it after v2.3.3, please reopen this issue.
