### ISSUE TITLE
I'm emmiting .stop and keeps de reference in background

### ISSUE THREAD

**Issue by Sk8er22** [yoheimuta/RxMusicPlayer#56]
Hello,

I have an issue. I have a screen where I instantiate a RxMusiclPlayer with the Item that I need.
It works perfectly.
But once I leave the viewscreen If I lock the screen keeps showing the panel to reproduce the audio although I have : 
viewDidDisappear{
```
        self.emitCommand.onNext(.stop)
        self.player?.player?.pause()
        self.player?.player?.replaceCurrentItem(with: nil)
        self.player = nil

```
}

Also, I go to another screen that instantiates another RxMusicPlayer. it works perfect but if I lock the screen the player panel over there plays two tracks at the same time. 

So it's like AVplayer panel from the lock screen keeps a reference two both RxMusicPlayer?

**Comment by yoheimuta** [comment]
@Sk8er22 Thank you for reaching out.
I'm looking into this.

**Comment by yoheimuta** [comment]
> But once I leave the viewscreen If I lock the screen keeps showing the panel to reproduce the audio although I have :

I could reproduce this problem. 
I'll fix it by #59.

> if I lock the screen the player panel over there plays two tracks at the same time.

I couldn't reproduce this.

> So it's like AVplayer panel from the lock screen keeps a reference two both RxMusicPlayer?

No. In theory and my digging locally, the lock screen doesn't have a reference to the RxMusicPlayer.

**Comment by Sk8er22** [comment]
Thank you very much! appreciate the library and your work :)

> if I lock the screen the player panel over there plays two tracks at the same time.
> So it's like AVplayer panel from the lock screen keeps a reference two both RxMusicPlayer?

If after apply the fix keeps happening I will upload a video and give you more information, but with` fix: Clear the now playing info center dictionary #59` I believe it will get fixed

**Comment by yoheimuta** [comment]
@Sk8er22 I think so! And uploading a video sounds helpful.

For now, I've cut a release here: https://github.com/yoheimuta/RxMusicPlayer/releases/tag/2.3.2

I'll publish it to cocoapod too shortly.

**Comment by yoheimuta** [comment]
Updating the cocoapod spec is done.
