### ISSUE TITLE
Boost volume

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#57]
Hey!
I poked around in your code and implemented the Sound Boost function
Default value player.volume = 1, can be changed to 2

If interested, I can throw off the implementation so that you can release an update

**Comment by yoheimuta** [comment]
@rastaman111 Thank you for letting me know.
As far as I know, the volume's max value is 1.0.
Is it worth setting it to 2.0?

> A value of 0.0 indicates silence; a value of 1.0 (the default) indicates full audio volume for the player instance.
>> https://developer.apple.com/documentation/avfoundation/avplayer/1390127-volume

**Comment by rastaman111** [comment]
Good afternoon @yoheimuta.  by default 1.0, but you can set any value, I put 2.0 on the switch and it works great :)

**Comment by rastaman111** [comment]
Hi, @yoheimuta 

File RxMusicPlayer func playVolume

Used - self.musicPlayer.player?.playVolume = value ? 2.0 : 1.0

[RxMusicPlayer.zip](https://github.com/yoheimuta/RxMusicPlayer/files/8966958/RxMusicPlayer.zip)

**Comment by yoheimuta** [comment]
@rastaman111 Thank you for elaborating on it.
Although I gave it a try setting the volume property to 1 and 2, I wasn't aware of the difference.

It looks like the document doesn't support the feature of boosting volume.
I'm closing this issue for now, but let me know when you have another solid ground for this.

**Comment by rastaman111** [comment]
@yoheimuta  I threw off the file where I implemented the sound boost, it is working, copy it as an independent library and check
