### ISSUE TITLE
Bug: player auto play next audio

### ISSUE THREAD

**Issue by ldthanh1993** [yoheimuta/RxMusicPlayer#58]
I have two screens A and B in a project.
A contains playerA and B contains playerB.
PlayerB plays the sound at index 5 and I stop it.
PlayerA plays the sound at index 1.
After the sound at index 1 end, Player A plays the sound at index 2 and playerB **automatically** next to 6.

I'm not certain that I'm using this library properly.
If it's a lib bug, please fix it.
If not, please show me how to fix it.

Thanks

**Comment by LinhNH2096** [comment]
Hi @rastaman111

**Comment by LinhNH2096** [comment]
@rastaman111

**Comment by LinhNH2096** [comment]
Hi @rastaman111 ,
In my case I have two different playlists. And I want them to exist at the same time but it seems the library can't manage the states of the two lists separately.  
Please tell me the best solution in this case. Tkanks!!!

**Comment by rastaman111** [comment]
@LinhNH2096 

I do not understand a little why you need to work with two lists at once.  if you do it as an audio player, then there if the playlists and they do not depend on each other

**Comment by ldthanh1993** [comment]
@rastaman111 
There are two tabs in my screen.
I don't want to play two lists at the same time.
But I want if I pause the audio at B it will keep the state and progress time.
It would be wrong for me to switch to another tab, play and next any sound in this tab

**Comment by rastaman111** [comment]
@LinhNH2096 
I understand you, you need to implement 2 heavy players and when you turn on another, this one slows down
