### ISSUE TITLE
RxMusic

### ISSUE THREAD

**Issue by alihajian-e** [yoheimuta/RxMusicPlayer#6]
Hi
I have 2 pages, one song player and the other song list.
I want to play a new song from this list every time and replace the new one with the previous one.

But both songs play together

**Comment by yoheimuta** [comment]
@alihajian-e Thank you for using it.

Can you share some more detailed information, such as code snippet, sample iOS project, or capture image/video? Especially, I want the sample code you're using.

I have previously implemented the app you're going to do, and it should work basically.

**Comment by alihajian-e** [comment]
[https://gofile.io/?c=ET9zLK](url)
Video app link👆

**Comment by yoheimuta** [comment]
@alihajian-e Thank you for sharing.
I'm going to investigate it.

**Comment by yoheimuta** [comment]
> I have previously implemented the app you're going to do, and it should work basically.

[memo] This one: https://github.com/yoheimuta/AMMusicPlayerController#demo

**Comment by yoheimuta** [comment]
@alihajian-e 

> I will email the original project to you

I looked over your project and found out that it had a problem with how to release your VC.

The cause is that you forget `[weak self]` that prevent disposing of the resources the seeming dismissed VC has. It's not relevant to the RxMusicPlayer.

- ref. https://www.avanderlee.com/swift/weak-self/

Bottom line is that you had better adapt to add `[weak self]` to each closure like below. That makes my local project resolve the issue.

```diff
- do(onNext: { index in
+ do(onNext: { [weak self] index in
```

```diff
- .drive(onNext: {
+ .drive(onNext: { [weak self] in
```

**Comment by alihajian-e** [comment]
Thank you very much

Another question I have is how do I control the song on another page?
Such as: playback, pause, etc.

**Comment by yoheimuta** [comment]
@alihajian-e You're welcome.

Your question is a bit out of the scope relating to the RxMusicPlayer, right?

In general, you should create an instance of RxMusicPlayer in your app and share it in all VCs(such as MusicPlayVC). In other words, I think it's hard to implement what you want by creating each RxMusicPlayer per VC. See the below link.

- ref. https://github.com/yoheimuta/AMMusicPlayerController/blob/master/AMMusicPlayerController/AMMusicPlayerController.swift#L33-L45

**Comment by alihajian-e** [comment]
Result: No way to stop and play the song on another page?
Or did I not understand what you meant?
Can you give more explanation?

**Comment by yoheimuta** [comment]
@alihajian-e 

> Result: No way to stop and play the song on another page?

Generally, it depends, but the RxPlayer itself can control the song regardless of the views system.
I think it may lack your information to answer your question properly.

> My other question is how to stop playing the song

The RxMusicPlayer supports the commands below, and you can send `stop` so that the player stops playing the song. If you have any trouble understanding its APIs, I'm willing to write some more API comments or documentation.

```swift
   /**
     Player Command.
     */
    public enum Command: Equatable {
        case play
        case playAt(index: Int)
        case next
        case previous
        case pause
        case stop
        case seek(seconds: Int, shouldPlay: Bool)
        /// fetch the metadata of the item with the current index without playing.
        case prefetch
```

**Comment by alihajian-e** [comment]
Thanks
But the stop command or other command doesn't work

 override func viewDidLoad() {
        super.viewDidLoad()
        Command.stop
     //   Command.prefetch
    }

I'm stuck and I don't know what to do and I need your help

If we can talk on Instagram or WhatsApp or anywhere else
very good

thanks again

**Comment by yoheimuta** [comment]
@alihajian-e 

> But the stop command or other command doesn't work

Well, you misunderstand the usage of running commands.
The only API to run the command is `player.run(cmd: cmd),` so writing just `Command.stop` is pointless.

If you follow the sample code in the README, you should add the extra commands to Driver.merge's argument, for example, like below.

```swift
let cmd = Driver.merge(
...
stopButton.rx.tap.asDriver().map { RxMusicPlayer.Command.stop },
)
```

If you find it hard, you may need to understand the RxSwift concepts through some tutorials beforehand.
