### ISSUE TITLE
Impossible to replace playing items

### ISSUE THREAD

**Issue by 0xacdc** [yoheimuta/RxMusicPlayer#67]
If I need to completely replace playing items, the only way to do this seems to be:
```
player.stop()

 self.player.queuedItems.enumerated().forEach { idx, value in   
      try? self.player.remove(at: idx)   
}

 self.player.append(items: newItems)
```

But this does not work. The `remove` will throw error when index will match `playIndex`, so if I'd like to call `play(at: index_from_the_new_items)` it will not be the one I want. 

So, what is the solution to stop the player, replaces all items. add new ones and play from desired index ?

**Comment by yoheimuta** [comment]
Hi @0xacdc 

Have you found a solution to replace playing items in the end?

**Comment by 0xacdc** [comment]
HI @yoheimuta, 

a solution may be:
```
  /**
     Clear player datasource
  */

    public func clearPlayingItems() {
        player?.pause()

        masterQueuedItems.removeAll()
        queuedItems.removeAll()
    }
```  

but after it will need: 
```
 private func play(atIndex index: Int) -> Observable<()> {
        if player != nil && playIndex == index && status == .paused {
            return resume()
        }
        player?.pause()

        guard queuedItems.indices.contains(index) else {
            return .just(())
        }
        ...
```

but because of return of empty Observable, there is no way to notify about what happened, and this is not the perfect solution

**Comment by yoheimuta** [comment]
@0xacdc Thanks for getting back to me. So, just to clarify, you haven't found a workaround yet, is that correct? And you closed the issue because a fix is no longer needed?

**Comment by 0xacdc** [comment]
Yes, for the moment I switched to high priority tasks. But I think It is a important and obvious feature for any player, how to play a list of tracks, and when user is selecting another track from another playlist replace entire queue ?
