### ISSUE TITLE
Don't updated speed locked screen

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#8]
Hello!
After scrolling, I’ll see progress at any time, NowPlayingInfoCenter is not updated on the locked screen
only if you click stop and again the strat, then it will be updated and it is also possible to turn on the audio playback speed at 2x NowPlayingInfoCenter is also not updated, the strip moves like usual 1x speed.

link to an example video: https://yadi.sk/i/znHUhyeHrdKekg

  var rate: Float = 1.0
    override func viewDidLoad() {
         super.viewDidLoad()
         
         rateSeekSpeed(self.rate)
    }
    func rateSeekSpeed(_ rate: Float) {
        
        musicPlayer.player?.rx.playerIndex()
        .do(onNext: { index in
            self.musicPlayer.player?.player?.rate = rate
        })
        .drive()
        .disposed(by: musicPlayer.disposeBag)
        
    }
    
    @IBAction func rateSpeedButton(_ sender: UIButton) {
        let alert = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        alert.addAction(UIAlertAction(title: "2x", style: .default, handler: { (alert) in
            self.rate = 2
            self.rateSeekSpeed(self.rate)
        }))
        alert.addAction(UIAlertAction(title: "1.5x", style: .default, handler: { (alert) in
            self.rate = 1.5
            self.rateSeekSpeed(self.rate)
        }))
        alert.addAction(UIAlertAction(title: "1.25x", style: .default, handler: { (alert) in
            self.rate = 1.25
            self.rateSeekSpeed(self.rate)
        }))
        alert.addAction(UIAlertAction(title: "1x", style: .default, handler: { (alert) in
            self.rate = 1
            self.rateSeekSpeed(self.rate)
        }))
        alert.addAction(UIAlertAction(title: "0.75x", style: .default, handler: { (alert) in
            self.rate = 0.75
            self.rateSeekSpeed(self.rate)
        }))
        alert.addAction(UIAlertAction(title: "0.5x", style: .default, handler: { (alert) in
            self.rate = 0.5
            self.rateSeekSpeed(self.rate)
        }))
        
        alert.addAction(UIAlertAction(title: "Отмена", style: .cancel, handler: nil))
        alert.view.tintColor = .black
        present(alert, animated: true, completion: nil)
    }

**Comment by yoheimuta** [comment]
@rastaman111 Thank you for reaching out.
I'm investigating it.

**Comment by yoheimuta** [comment]
I found out that the RxMusicPlayer needs built-in support for the playback rate.
I'm going to add the feature.

**Comment by rastaman111** [comment]
Hello!  Thank you, I look forward to an update.

**Comment by rastaman111** [comment]
Hello!
I found another bug with playback speed

I turn on the audio, select a speed of 2x, press pause and when I click play the speed becomes 1x by default

**Comment by yoheimuta** [comment]
[memo] It's almost finished, except for a confirmation with a device, which my local preparation is taking some time.

**Comment by rastaman111** [comment]
Hello!
I did not quite understand
You did, but it remains to check everything on a real device?

**Comment by yoheimuta** [comment]
@rastaman111 I updated the master branch to add the feature.
Can you confirm it works fine?

**Comment by rastaman111** [comment]
Hi. where can i find your update?

**Comment by yoheimuta** [comment]
@rastaman111 Can you elaborate?
I updated the master branch of this repository.

**Comment by yoheimuta** [comment]
I plan to update the Podspec after your confirmation.
If you want the updated Pod now, I can do it ahead of that.

**Comment by rastaman111** [comment]
Hi, we checked it for how everything works, but can you tick the end of the selected speed?  Example 1x ✓

**Comment by yoheimuta** [comment]
Thank you for your confirmation.

Yes. I added a tick at the end.

- https://github.com/yoheimuta/RxMusicPlayer/commit/3939883f93d8d98c445c7812887b28da424279c3
